name: "gbraad's Dotfiles `install` action"
description: "Install my dotfiles to automate developer environment and virtual machine related tasks"
author: "Gerard Braad <me@gbraad.nl>"

inputs:
  change-shell:
    description: "Whether to change the user's shell to zsh after installation"
    required: false
    default: "true"
  sudo-change-shell:
    description: "Use sudo when changing the shell"
    required: false
    default: "false"
  user:
    description: "The username for which to change the shell"
    required: false
    default: "runner"
  upstream:
    description: "Whether to use the upstream dotfiles repository"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Install dotfiles
      run: |
        if [ "${{ inputs.upstream }}" = "true" ]; then
          git clone https://github.com/gbraad-dotfiles/upstream.git ~/.dotfiles --depth 2
          cd ~/.dotfiles
          sh ./install.sh
        else
          curl -fsSL https://dotfiles.gbraad.nl/install.sh | sh
        fi

        if [ "${{ inputs.change-shell }}" = "true" ]; then
          SHELL_PATH="$(which zsh)"
          TARGET_USER="${{ inputs.user }}"
          if [ "${{ inputs.sudo-change-shell }}" = "true" ]; then
            sudo chsh -s "$SHELL_PATH" "$TARGET_USER"
          else
            chsh -s "$SHELL_PATH"
          fi
        fi
      shell: bash
