name: "gbraad's Dotfiles `install` action"
description: "Install my dotfiles to automate developer environment and virtual machine related tasks"
author: "Gerard Braad <me@gbraad.nl>"
runs:
  using: "composite"
  steps:
    - name: Install dotfiles
      run: |
        curl -fsSL https://dotfiles.gbraad.nl/install.sh | sh
        chsh -s $(which zsh) || true
      shell: bash
